# METAR GeoParquet Analysis and Visualization
---

## Overview
   
Within this notebook, we will cover:

1. Browser-based interactive maps of point-based data 
1. [Geopandas](https://geopandas.org/en/stable/)

## Prerequisites
| Concepts | Importance | Notes |
| --- | --- | --- |
| [Cartopy Intro](https://foundations.projectpythia.org/core/cartopy/cartopy.html) | Required | Projections and Features |
| [Pandas](https://foundations.projectpythia.org/core/pandas.html) | Required | Tabular Datasets |

- **Time to learn**: 20 minutes
---

## Imports

In [1]:
import matplotlib.pyplot as plt
import pandas as pd
from cartopy import crs as ccrs
from cartopy import feature as cfeature
from datetime import datetime,timedelta
from dateutil.relativedelta import relativedelta

import geopandas as gpd
from lonboard import viz, Map, ScatterplotLayer, HeatmapLayer
import duckdb

In [2]:
con = duckdb.connect()

In [3]:
duckdb.install_extension("spatial", connection=con)
duckdb.load_extension("spatial", connection=con)

### Explore a monthly METAR Parquet file

In [4]:
sample = gpd.read_parquet(f'yearly/2022-2024_metar.parquet')

In [5]:
sample

,STN,YYMMDD/HHMM,LAT,LON,Elevation,PMSL,ALTI,TMPC,DWPC,SKNT,...,CTYH,P06I,T6XC,T6NC,CEIL,P01I,SNEW,HEAT,WCHT,geometry
Time,,,,,,,,,,,,,,,,,,,,,
2022-01-01 00:00:00+00:00,04V,220101/0000,38.10,-106.17,2385.0,NaN,29.45,0.0,-9.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.00,25.56,POINT (-106.17 38.1)
2022-01-01 00:00:00+00:00,0CO,220101/0000,39.79,-105.76,3807.0,NaN,29.36,-14.0,-16.0,12.0,...,NaN,NaN,NaN,NaN,5.0,NaN,NaN,6.80,-10.02,POINT (-105.76 39.79)
2022-01-01 00:00:00+00:00,11R,220101/0000,30.22,-96.37,94.0,NaN,29.71,24.5,20.0,9.0,...,NaN,NaN,28.2,24.5,NaN,NaN,NaN,76.98,76.10,POINT (-96.37 30.22)
2022-01-01 00:00:00+00:00,12N,220101/0000,41.01,-74.74,178.0,1014.0,29.93,9.4,8.3,4.0,...,NaN,NaN,10.0,8.3,NaN,NaN,NaN,47.88,47.20,POINT (-74.74 41.01)
2022-01-01 00:00:00+00:00,1A5,220101/0000,35.22,-83.42,616.0,NaN,30.02,12.1,11.6,0.0,...,NaN,0.07,13.6,11.7,10.0,0.05,NaN,53.41,53.78,POINT (-83.42 35.22)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-12-31 23:00:00+00:00,1LN,241231/2300,48.79,-102.27,601.0,1023.8,30.10,-12.0,-14.6,20.0,...,NaN,NaN,NaN,NaN,15.0,NaN,NaN,10.40,-9.50,POINT (-102.27 48.79)
2024-12-31 23:00:00+00:00,1MN,241231/2300,48.67,-101.88,569.0,1023.6,30.10,-12.6,-15.1,19.0,...,NaN,NaN,NaN,NaN,16.0,NaN,NaN,9.32,-10.51,POINT (-101.88 48.67)
2024-12-31 23:00:00+00:00,1YT,241231/2300,46.66,-120.45,438.0,1022.3,30.14,2.2,-0.6,0.0,...,NaN,NaN,NaN,NaN,15.0,NaN,NaN,35.96,35.96,POINT (-120.45 46.66)
2024-12-31 23:00:00+00:00,GDK,241231/2300,39.69,-83.99,289.0,NaN,29.52,5.0,5.0,9.0,...,NaN,NaN,NaN,NaN,9.0,0.01,NaN,39.50,34.73,POINT (-83.99 39.69)
2024-12-31 23:00:00+00:00,GMFM,241231/2300,33.87,-5.52,549.0,NaN,30.27,4.0,0.0,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.20,33.01,POINT (-5.52 33.87)

In [10]:
subset = sample.query ('Time >= "2024-06-25T00:00:00 UTC" & Time <= "2024-06-25T23:00:00 UTC" & TDXC >= 37.8' )

In [11]:
subset['Time'] = subset.index

/knight/jan25/envs/jan26_env/lib/python3.14/site-packages/geopandas/geodataframe.py:1969: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

In [12]:
sub1 = subset.set_index('STN')

In [13]:
sub1

,YYMMDD/HHMM,LAT,LON,Elevation,PMSL,ALTI,TMPC,DWPC,SKNT,DRCT,...,P06I,T6XC,T6NC,CEIL,P01I,SNEW,HEAT,WCHT,geometry,Time
STN,,,,,,,,,,,,,,,,,,,,,
JWG,240625/0000,35.87,-98.42,472.0,NaN,29.87,35.5,16.7,12.0,170.0,...,NaN,39.0,35.4,NaN,NaN,NaN,96.95,95.90,POINT (-98.42 35.87),2024-06-25 00:00:00+00:00
BPG,240625/0000,32.22,-101.52,784.0,NaN,29.88,37.1,12.7,14.0,170.0,...,NaN,38.0,33.1,NaN,NaN,NaN,97.10,98.78,POINT (-101.52 32.22),2024-06-25 00:00:00+00:00
K82,240625/0000,39.76,-98.79,549.0,NaN,29.71,39.9,14.8,15.0,190.0,...,NaN,43.5,39.5,NaN,NaN,NaN,104.29,103.82,POINT (-98.79 39.76),2024-06-25 00:00:00+00:00
VHN,240625/0000,31.06,-104.78,1206.0,NaN,29.94,38.1,8.6,7.0,80.0,...,NaN,39.0,33.4,NaN,NaN,NaN,97.03,100.58,POINT (-104.78 31.06),2024-06-25 00:00:00+00:00
OJA,240625/0000,35.54,-98.67,489.0,NaN,29.86,35.7,17.6,14.0,190.0,...,NaN,38.6,35.6,NaN,NaN,NaN,98.28,96.26,POINT (-98.67 35.54),2024-06-25 00:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CPU,240625/0800,38.15,-120.65,404.0,NaN,29.90,23.0,7.7,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,72.20,73.40,POINT (-120.65 38.15),2024-06-25 08:00:00+00:00
QRH,240625/2100,11.55,43.17,10.0,999.2,NaN,37.4,18.6,5.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,103.12,99.32,POINT (43.17 11.55),2024-06-25 21:00:00+00:00
OKAS,240625/2100,29.35,47.35,144.0,995.9,NaN,36.6,7.6,11.0,300.0,...,NaN,NaN,NaN,NaN,NaN,NaN,94.01,97.88,POINT (47.35 29.35),2024-06-25 21:00:00+00:00
OTBH,240625/2100,25.12,51.32,40.0,994.2,NaN,34.9,18.0,8.0,330.0,...,NaN,NaN,NaN,NaN,NaN,NaN,97.05,94.82,POINT (51.32 25.12),2024-06-25 21:00:00+00:00
OEPS,240625/2200,24.07,47.58,503.0,1000.0,NaN,34.3,1.6,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,89.13,93.74,POINT (47.58 24.07),2024-06-25 22:00:00+00:00

In [15]:
sub1.explore?

Signature: sub1.explore(*args, **kwargs) -> 'folium.Map'
Docstring:
Explore data in interactive map based on GeoPandas and folium/leaflet.js.

Generate an interactive leaflet map based on :class:`~geopandas.GeoDataFrame`

Parameters
----------
column : str, np.array, pd.Series (default None)
    The name of the dataframe column, :class:`numpy.array`,
    or :class:`pandas.Series` to be plotted. If :class:`numpy.array` or
    :class:`pandas.Series` are used then it must have same length as dataframe.
cmap : str, matplotlib.Colormap, branca.colormap or function (default None)
    The name of a colormap recognized by ``matplotlib``, a list-like of colors,
    :class:`matplotlib.colors.Colormap`, a :class:`branca.colormap.ColorMap` or
    function that returns a named color or hex based on the column
    value, e.g.::

        def my_colormap(value):  # scalar value defined in 'column'
            if value > 1:
                return "green"
            return "red"

color : str, array-like (default None)
    Named color or a list-like of colors (named or hex).
m : folium.Map (default None)
    Existing map instance on which to draw the plot.
tiles : str, xyzservices.TileProvider (default 'OpenStreetMap Mapnik')
    Map tileset to use. Can choose from the list supported by folium, query a
    :class:`xyzservices.TileProvider` by a name from ``xyzservices.providers``,
    pass :class:`xyzservices.TileProvider` object or pass custom XYZ URL.
    The current list of built-in providers (when ``xyzservices`` is not available):

    ``["OpenStreetMap", "CartoDB positron", “CartoDB dark_matter"]``

    You can pass a custom tileset to Folium by passing a Leaflet-style URL
    to the tiles parameter: ``http://{s}.yourtiles.com/{z}/{x}/{y}.png``.
    Be sure to check their terms and conditions and to provide attribution with
    the ``attr`` keyword.
attr : str (default None)
    Map tile attribution; only required if passing custom tile URL.
tooltip : bool, str, int, list (default True)
    Display GeoDataFrame attributes when hovering over the object.
    ``True`` includes all columns. ``False`` removes tooltip. Pass string or list of
    strings to specify a column(s). Integer specifies first n columns to be
    included. Defaults to ``True``.
popup : bool, str, int, list (default False)
    Input GeoDataFrame attributes for object displayed when clicking.
    ``True`` includes all columns. ``False`` removes popup. Pass string or list of
    strings to specify a column(s). Integer specifies first n columns to be
    included. Defaults to ``False``.
highlight : bool (default True)
    Enable highlight functionality when hovering over a geometry.
categorical : bool (default False)
    If ``False``, ``cmap`` will reflect numerical values of the
    column being plotted. For non-numerical columns, this
    will be set to True.
legend : bool (default True)
    Plot a legend in choropleth plots.
    Ignored if no ``column`` is given.
scheme : str (default None)
    Name of a choropleth classification scheme (requires ``mapclassify`` >= 2.4.0).
    A :func:`mapclassify.classify` will be used
    under the hood. Supported are all schemes provided by ``mapclassify`` (e.g.
    ``'BoxPlot'``, ``'EqualInterval'``, ``'FisherJenks'``, ``'FisherJenksSampled'``,
    ``'HeadTailBreaks'``, ``'JenksCaspall'``, ``'JenksCaspallForced'``,
    ``'JenksCaspallSampled'``, ``'MaxP'``, ``'MaximumBreaks'``,
    ``'NaturalBreaks'``, ``'Quantiles'``, ``'Percentiles'``, ``'StdMean'``,
    ``'UserDefined'``). Arguments can be passed in ``classification_kwds``.
k : int (default 5)
    Number of classes
vmin : None or float (default None)
    Minimum value of ``cmap``. If ``None``, the minimum data value
    in the column to be plotted is used.
vmax : None or float (default None)
    Maximum value of ``cmap``. If ``None``, the maximum data value
    in the column to be plotted is used.
width : pixel int or percentage string (default: '100%')
    Width of the folium :class:`~folium.folium.Map`. If the argument
    m is given explicitly, width is ignored.
height : pixel int or percentage string (default: '100%')
    Height of the folium :class:`~folium.folium.Map`. If the argument
    m is given explicitly, height is ignored.
categories : list-like
    Ordered list-like object of categories to be used for categorical plot.
classification_kwds : dict (default None)
    Keyword arguments to pass to mapclassify
control_scale : bool, (default True)
    Whether to add a control scale on the map.
marker_type : str, folium.Circle, folium.CircleMarker, folium.Marker (default None)
    Allowed string options are ('marker', 'circle', 'circle_marker'). Defaults to
    folium.CircleMarker.
marker_kwds: dict (default {})
    Additional keywords to be passed to the selected ``marker_type``, e.g.:

    radius : float (default 2 for ``circle_marker`` and 50 for ``circle``))
        Radius of the circle, in meters (for ``circle``) or pixels
        (for ``circle_marker``).
    fill : bool (default True)
        Whether to fill the ``circle`` or ``circle_marker`` with color.
    icon : folium.map.Icon
        the :class:`folium.map.Icon` object to use to render the marker.
    draggable : bool (default False)
        Set to True to be able to drag the marker around the map.

style_kwds : dict (default {})
    Additional style to be passed to folium ``style_function``:

    stroke : bool (default True)
        Whether to draw stroke along the path. Set it to ``False`` to
        disable borders on polygons or circles.
    color : str
        Stroke color
    weight : int
        Stroke width in pixels
    opacity : float (default 1.0)
        Stroke opacity
    fill : boolean (default True)
        Whether to fill the path with color. Set it to ``False`` to
        disable filling on polygons or circles.
    fillColor : str
        Fill color. Defaults to the value of the color option
    fillOpacity : float (default 0.5)
        Fill opacity.
    style_function : callable
        Function mapping a GeoJson Feature to a style ``dict``.

        * Style properties :func:`folium.vector_layers.path_options`
        * GeoJson features :class:`GeoDataFrame.__geo_interface__`

        e.g.::

            lambda x: {"color":"red" if x["properties"]["gdp_md_est"]<10**6
                                         else "blue"}

    Plus all supported by :func:`folium.vector_layers.path_options`. See the
    documentation of :class:`folium.features.GeoJson` for details.

highlight_kwds : dict (default {})
    Style to be passed to folium highlight_function. Uses the same keywords
    as ``style_kwds``. When empty, defaults to ``{"fillOpacity": 0.75}``.
missing_kwds : dict (default {})
    Additional style for missing values:

    color : str
        Color of missing values. Defaults to ``None``, which uses Folium's default.
    label : str (default "NaN")
        Legend entry for missing values.
tooltip_kwds : dict (default {})
    Additional keywords to be passed to :class:`folium.features.GeoJsonTooltip`,
    e.g. ``aliases``, ``labels``, or ``sticky``.
popup_kwds : dict (default {})
    Additional keywords to be passed to :class:`folium.features.GeoJsonPopup`,
    e.g. ``aliases`` or ``labels``.
legend_kwds : dict (default {})
    Additional keywords to be passed to the legend.

    Currently supported customisation:

    caption : string
        Custom caption of the legend. Defaults to the column name.

    Additional accepted keywords when ``scheme`` is specified:

    colorbar : bool (default True)
        An option to control the style of the legend. If True, continuous
        colorbar will be used. If False, categorical legend will be used for bins.
    scale : bool (default True)
        Scale bins along the colorbar axis according to the bin edges (True)
        or use the equal length for each bin (False)
    fmt : string (default "{:.2f}")
        A formatting specification for the bin edges of the classes in the
        legend. For example, to have no decimals: ``{"fmt": "{:.0f}"}``. Applies
        if ``colorbar=False``.
    labels : list-like
        A list of legend labels to override the auto-generated labels.
        Needs to have the same number of elements as the number of
        classes (`k`). Applies if ``colorbar=False``.
    interval : boolean (default False)
        An option to control brackets from mapclassify legend.
        If True, open/closed interval brackets are shown in the legend.
        Applies if ``colorbar=False``.
    max_labels : int, default 10
        Maximum number of colorbar tick labels (requires branca>=0.5.0)
map_kwds : dict (default {})
    Additional keywords to be passed to folium :class:`~folium.folium.Map`,
    e.g. ``dragging``, or ``scrollWheelZoom``.


**kwargs : dict
    Additional options to be passed on to the folium object.

Returns
-------
m : folium.folium.Map
    folium :class:`~folium.folium.Map` instance

Examples
--------
>>> import geodatasets
>>> df = geopandas.read_file(
...     geodatasets.get_path("geoda.chicago_health")
... )
>>> df.head(2)  # doctest: +SKIP
   ComAreaID  ...                                           geometry
0         35  ...  POLYGON ((-87.60914 41.84469, -87.60915 41.844...
1         36  ...  POLYGON ((-87.59215 41.81693, -87.59231 41.816...

[2 rows x 87 columns]

>>> df.explore("Pop2012", cmap="Blues")  # doctest: +SKIP
File:      /knight/jan25/envs/jan26_env/lib/python3.14/site-packages/geopandas/geodataframe.py
Type:      method

In [16]:
m = sub1.explore(color='purple')

In [18]:
# Add title
import folium

title_html = """
<h3 align="center" style="font-size:20px">
    <b>Temperatures >= 100 ° F, 6/24/2024</b>
</h3>
"""

m.get_root().html.add_child(folium.Element(title_html))

# Save or display
m.save("map.html")

In [20]:
m

In [ ]:
db = duckdb.read_parquet(f'monthly/concatenated_file.parquet')

In [ ]:
db.sql('SHOW ALL TABLES')

In [ ]:
%%time
sql = """
CREATE TABLE metar AS
SELECT 
    Time, STN, TMPC, DWPC, PMSL, ALTI,
    ST_Point(LON, LAT) as geometry
FROM "s3://us-west-2.opendata.source.coop/ktyle/metar2024/2024_metar.parquet" 
WHERE
    Time BETWEEN '2024-06-29 18:00:00' AND '2024-06-29 18:00:00'
LIMIT 1_000_000;
"""
con.execute(sql)

In [ ]:
%%time
sql = """
CREATE TABLE warmhumid AS
SELECT 
    Time, STN, TMPC, DWPC, PMSL, ALTI,
    ST_Point(LON, LAT) as geometry
FROM "s3://us-west-2.opendata.source.coop/ktyle/metar2024/2024_metar.parquet" 
WHERE
    TMPC >= 27 AND
    TMPC <= 30 AND
    DWPC >= 21 AND
    DWPC <= 28
    
--LIMIT 1_000_000;
"""
db = con.execute(sql)

In [ ]:
url = "s3://us-west-2.opendata.source.coop/ktyle/metar2024/2024_metar.parquet"

In [ ]:
url

In [ ]:
sql = f"""CREATE TABLE nys_dec2024 AS

In [ ]:
sql0 = """
PREPARE query AS 
  SELECT STN, TMPC, DWPC, PMSL,  "YYMMDD/HHMM" as DATTIM, 
  ST_Point(LON, LAT) as geometry
---FROM "s3://us-west-2.opendata.source.coop/ktyle/metar2024/2024_metar.parquet"
  FROM $url
  WHERE
    LON >= -80 AND
    LAT >= 40 AND
    LON <= -72 AND
    LAT <= 45 AND
    Time BETWEEN '2024-12-01 00:00:00' AND '2024-12-31 23:59:59';
"""

In [ ]:
sql = f"""CREATE TABLE nys_dec2024 AS 
SELECT STN, TMPC, DWPC, PMSL,  "YYMMDD/HHMM" as DATTIM, 
ST_Point(LON, LAT) as geometry
---FROM "s3://us-west-2.opendata.source.coop/ktyle/metar2024/2024_metar.parquet"
FROM $url
WHERE
    LON >= -80 AND
    LAT >= 40 AND
    LON <= -72 AND
    LAT <= 45 AND
    Time BETWEEN '2024-12-01 00:00:00' AND '2024-12-31 23:59:59';
"""

In [ ]:
con.query?

In [ ]:
con.execute(f"{sql0}, {url}")

In [ ]:
db = con.execute(sql,url=$url)

In [ ]:
sql = """
CREATE TABLE warmhumid AS
SELECT 
    STN, TMPC, DWPC, PMSL,  "YYMMDD/HHMM" as DATTIM,
    ST_Point(LON, LAT) as geometry
FROM "yearly/2024_metar.parquet" 
WHERE
    LON >= -74 AND
    LAT >= 42.6 AND
    LON <= -73.5 AND
    LAT <= 42.8 AND
    Time BETWEEN '2024-01-01 00:00:00' AND '2024-12-31 23:59:00'
    LIMIT 1_000_000;
"""
db = con.execute(sql)

In [ ]:
db.sql('SHOW ALL TABLES')

In [ ]:
con.execute("DROP TABLE metar")

In [ ]:
#df = db.df()

In [ ]:
table = con.table("metar")

df = table.df()

df

In [ ]:
df[df['TMPC'] > 24]

In [ ]:
sql = """
CREATE TABLE heat AS
SELECT 
    Time, STN, TMPC, DWPC, HEAT,
    "YYMMDD/HHMM" as DATTIM,
    ST_Point(LON, LAT) as geometry
FROM "monthly/2024_metar.parquet" 
WHERE
    HEAT > 100 AND
    LAT > 40 AND
    LAT < 45 AND
    LON > -80 AND
    LON < -71 AND
    Time BETWEEN '2024-06-01 00:00:00' AND '2024-06-26 00:00:00'
LIMIT 1_000_000;
"""
con.execute(sql)

In [ ]:
sql = """
CREATE TABLE tmpc AS
SELECT 
--    TMPC,
    Time, STN, TMPC, DWPC, HEAT, "YYMMDD/HHMM",
    ST_Point(LON, LAT) as geometry
FROM "monthly/concatenated_file.parquet" 
--FROM "yearly/2024_metar.parquet" 
WHERE
    LON >= -80 AND
    LAT >= 37 AND
    LON <= -65 AND
    LAT <= 45 AND
    Time BETWEEN '2024-11-01 00:00:00' AND '2024-11-26 00:00:00' AND
    TMPC > 28
LIMIT 1_000_000;
"""
con.execute(sql)

In [ ]:
con.execute("DROP TABLE metar")

In [ ]:
layer = ScatterplotLayer.from_duckdb(con.table("metar"), con, radius_min_pixels=2.5)

In [ ]:
m = Map(layer)

May run into a JavaScript error if running from JupyterHub, likely due to lack of `anywidget` package in the Jupyterhub environment.

In [ ]:
m

In [ ]:
db.close()

In [ ]:
duckdb.query('''
   SELECT *
   FROM 'db'
   WHERE TMPC BETWEEN '22.0' AND '24.0' AND Time BETWEEN '2024-06-23 00:00:00' AND '2024-06-23 02:00:00'
''')

In [ ]:
duckdb.query('''
   SELECT *
   FROM '20240623_metar.parquet'
   WHERE TMPC BETWEEN '22.0' AND '24.0' AND Time BETWEEN '2024-06-23 00:00:00' AND '2024-06-23 02:00:00'
''')

In [ ]:
db.

In [ ]:
viz(sample.loc['2024-06-23T23:00'])

In [ ]:
sample.explore('TMPC')

In [ ]:
gdfWorldMetar.explore(column='TMPC')

<div class="alert alert-info"><b>Note: </b> Most of the non-US data is not available until approximately 15 minutes past each hour. If you do not see many worldwide stations, try re-reading the data file after that point in the hour.</div>

<div class="alert alert-warning"><b>Exercise: </b> Create a color-coded map from one variable in the dataset.</div>

In [ ]:
# Write your code here
gdfWorldMetar.explore(column='TMPC')

<div class="alert alert-info">Note that the color scale is unaffected by any location whose temperature value was missing ... GeoPandas "knows" to exlucde <code>NaN</code> from the range of valid values.</div>

Plot hourly precipitation

In [ ]:
gdfWorldMetar.explore(column='P01M')

<div class="alert alert-info">With few exceptions, hourly precip is only provided by US stations. For this variable, a better visualization would exclude all the missing values (in the US, a missing value denotes <b>no precip</b>, while a <b>trace</b> = 0.00)</div>

In [ ]:
gdfWorldMetar = gdfWorldMetar.dropna(subset=['P01M']).reset_index(drop=True)

In [ ]:
gdfWorldMetar.explore(column='P01M')

## References

1. [GeoPandas](https://geopandas.org)
1. [EPSG](https://epsg.io)